// Render the cached stories as an RSS 2.0 feed.
import { Feed } from "feed";
import { FEED_URL, HN_COMMENTS_URL, PUBLIC_ORIGIN } from "./config.js";
import type { CachedStory } from "./cache.js";
import {
  escapeAttr,
  escapeHtml,
  selectStories,
  statsLine,
  summaryHtml,
} from "./html.js";

export function buildFeedXml(
  stories: CachedStory[],
  opts: { count: number; minPoints: number; updatedAt: number },
): string {
  const selected = selectStories(stories, opts);

  const feed = new Feed({
    title: "Hacker News Best — AI Summarized",
    description:
      "Top Hacker News stories, each with an AI-generated summary plus links to the original article and the HN discussion.",
    id: FEED_URL,
    link: PUBLIC_ORIGIN,
    language: "en",
    generator: "hn-summaries",
    copyright: "Story content © its authors; summaries generated by AI.",
    updated: new Date(opts.updatedAt || Date.now()),
    feedLinks: { rss: FEED_URL },
    ttl: 60,
  });

  for (const s of selected) {
    const hnUrl = HN_COMMENTS_URL(s.id);
    const articleLink = s.url ?? hnUrl;
    const posted = new Date(s.time * 1000);
    feed.addItem({
      title: s.title,
      id: hnUrl, // stable guid
      link: articleLink, // clicking the title opens the original article
      date: posted,
      published: posted,
      description: buildEntryHtml(s, articleLink, hnUrl),
    });
  }

  return feed.rss2();
}

function buildEntryHtml(
  s: CachedStory,
  articleLink: string,
  hnUrl: string,
): string {
  const fallbackNote = s.isFallback
    ? "<p><em>(Article unavailable — summary based on the HN discussion and title.)</em></p>\n"
    : "";
  return (
    `${fallbackNote}` +
    `${summaryHtml(s.summary)}\n` +
    `<p>👉 <a href="${escapeAttr(articleLink)}">Original article</a>` +
    ` &nbsp;·&nbsp; ` +
    `💬 <a href="${escapeAttr(hnUrl)}">HN comments</a></p>\n` +
    `<p><small>${escapeHtml(statsLine(s))}</small></p>`
  );
}
