// Render the cached stories as an RSS 2.0 feed.
import { Feed } from "feed";
import {
  DEFAULT_FEED_SORT,
  FEED_URL,
  HN_COMMENTS_URL,
  PUBLIC_ORIGIN,
  type FeedSort,
} from "./config.js";
import type { CachedStory } from "./cache.js";
import {
  bestListSize,
  escapeAttr,
  escapeHtml,
  rankStanding,
  selectStories,
  statsLine,
  summaryHtml,
  summaryTime,
} from "./html.js";

/** Self URL for a given sort — the default sort keeps the bare /feed URL so existing
 *  subscribers are unaffected; other sorts carry the explicit ?sort= param. */
function feedUrlFor(sort: FeedSort): string {
  return sort === DEFAULT_FEED_SORT ? FEED_URL : `${FEED_URL}?sort=${sort}`;
}

export function buildFeedXml(
  stories: CachedStory[],
  opts: { count: number; minPoints: number; sort: FeedSort; updatedAt: number },
): string {
  const listSize = bestListSize(stories);
  const selected = selectStories(stories, opts);
  const url = feedUrlFor(opts.sort);

  const feed = new Feed({
    title:
      opts.sort === "points"
        ? "Hacker News Best — AI Summarized (Top by points)"
        : "Hacker News Best — AI Summarized (Newest first)",
    description:
      opts.sort === "points"
        ? "The HN “best” list ranked by points, each with an AI summary. A story drops out the moment it leaves the best list."
        : "Top Hacker News stories newest-first, each with an AI summary of the article and the discussion.",
    id: url, // distinct id per sort so a reader treats the two views as separate feeds
    link: PUBLIC_ORIGIN,
    language: "en",
    generator: "hn-summaries",
    copyright: "Story content © its authors; summaries generated by AI.",
    updated: new Date(opts.updatedAt || Date.now()),
    feedLinks: { rss: url },
    ttl: 60,
  });

  for (const s of selected) {
    const hnUrl = HN_COMMENTS_URL(s.id);
    const articleLink = s.url ?? hnUrl;
    // Item date = when the summary was generated, so newly-summarized stories surface at the
    // top of a date-sorting reader (the original HN post time left the feed looking frozen).
    const date = new Date(summaryTime(s));
    feed.addItem({
      title: s.title,
      id: hnUrl, // stable guid (same story = same id across both sort views)
      link: articleLink, // clicking the title opens the original article
      date,
      published: date,
      description: buildEntryHtml(s, articleLink, hnUrl, opts.sort, listSize),
    });
  }

  return feed.rss2();
}

function buildEntryHtml(
  s: CachedStory,
  articleLink: string,
  hnUrl: string,
  sort: FeedSort,
  listSize: number,
): string {
  const standing = rankStanding(s, listSize);
  // Surface best-list standing so the points view makes roll-off visible, and the date view
  // explains why an off-list story is still here.
  let standingLine = "";
  if (sort === "points") {
    const warn = standing.nearRolloff
      ? " — ⚠ near the bottom, about to roll off"
      : "";
    standingLine = `<p><small>📊 ${escapeHtml(standing.label)}${warn}</small></p>\n`;
  } else if (standing.offList) {
    standingLine = `<p><small>⤓ ${escapeHtml(standing.label)} — kept in the newest view until it ages out</small></p>\n`;
  }
  const fallbackNote = s.isFallback
    ? "<p><em>(Article unavailable — summary based on the HN discussion and title.)</em></p>\n"
    : "";
  return (
    `${standingLine}` +
    `${fallbackNote}` +
    `${summaryHtml(s.summary)}\n` +
    `<p>👉 <a href="${escapeAttr(articleLink)}">Original article</a>` +
    ` &nbsp;·&nbsp; ` +
    `💬 <a href="${escapeAttr(hnUrl)}">HN comments</a></p>\n` +
    `<p><small>${escapeHtml(statsLine(s))}</small></p>`
  );
}
